<?php 
$table = array("
CREATE TABLE IF NOT EXISTS `^12340_gem_properties` (
  `id` int(11) NOT NULL,
  `spell_enchantement` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_item_enchantment` (
  `id` int(11) NOT NULL,
  `charges` int(11) NOT NULL,
  `display_type_1` int(11) NOT NULL,
  `display_type_2` int(11) NOT NULL,
  `display_type_3` int(11) NOT NULL,
  `amount_1` int(11) NOT NULL,
  `amount_2` int(11) NOT NULL,
  `amount_3` int(11) NOT NULL,
  `amount1_1` int(11) NOT NULL,
  `amount1_2` int(11) NOT NULL,
  `amount1_3` int(11) NOT NULL,
  `spellid_1` int(11) NOT NULL,
  `spellid_2` int(11) NOT NULL,
  `spellid_3` int(11) NOT NULL,
  `description` longtext NOT NULL,
  `aura_id` int(11) NOT NULL,
  `slot` int(11) NOT NULL,
  `GemID` int(11) NOT NULL,
  `EnchantmentCondition` int(11) NOT NULL,
  `requiredSkill` int(11) NOT NULL,
  `requiredSkillRank` int(11) NOT NULL,
  `requiredLevel` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_item_icon` (
  `id` int(11) NOT NULL DEFAULT '0',
  `name` longtext NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_item_set` (
  `id_set` int(11) NOT NULL,
  `Name_set_ru_ru` longtext,
  `item_set_id_1` int(11) DEFAULT NULL,
  `item_set_id_2` int(11) DEFAULT NULL,
  `item_set_id_3` int(11) DEFAULT NULL,
  `item_set_id_4` int(11) DEFAULT NULL,
  `item_set_id_5` int(11) DEFAULT NULL,
  `item_set_id_6` int(11) DEFAULT NULL,
  `item_set_id_7` int(11) DEFAULT NULL,
  `item_set_id_8` int(11) DEFAULT NULL,
  `item_set_id_9` int(11) DEFAULT NULL,
  `item_set_name_1` longtext,
  `item_set_name_2` longtext,
  `item_set_name_3` longtext,
  `item_set_name_4` longtext,
  `item_set_name_5` longtext,
  `item_set_name_6` longtext,
  `item_set_name_7` longtext,
  `item_set_name_8` longtext,
  `item_set_name_9` longtext,
  `spell_set_id_1` int(11) DEFAULT NULL,
  `spell_set_id_2` int(11) DEFAULT NULL,
  `spell_set_id_3` int(11) DEFAULT NULL,
  `spell_set_id_4` int(11) DEFAULT NULL,
  `spell_set_id_5` int(11) DEFAULT NULL,
  `spell_set_id_6` int(11) DEFAULT NULL,
  `spell_set_id_7` int(11) DEFAULT NULL,
  `spell_set_id_8` int(11) DEFAULT NULL,
  `spell_set_id_9` int(11) DEFAULT NULL,
  `amount_item_set__1` int(11) DEFAULT NULL,
  `amount_item_set__2` int(11) DEFAULT NULL,
  `amount_item_set__3` int(11) DEFAULT NULL,
  `amount_item_set__4` int(11) DEFAULT NULL,
  `amount_item_set__5` int(11) DEFAULT NULL,
  `amount_item_set__6` int(11) DEFAULT NULL,
  `amount_item_set__7` int(11) DEFAULT NULL,
  `amount_item_set__8` int(11) DEFAULT NULL,
  `Skill_line_id` int(11) DEFAULT NULL,
  `amount_Skill_line` int(11) DEFAULT NULL,
  PRIMARY KEY (`id_set`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_skill_line` (
  `id` int(11) NOT NULL,
  `Category` int(11) NOT NULL,
  `Unk1` int(11) NOT NULL,
  `Name` longtext NOT NULL,
  `Description` longtext NOT NULL,
  `iconId` int(11) NOT NULL,
  `alternateVerb` longtext NOT NULL,
  `canLink` int(11) NOT NULL,
  PRIMARY KEY (`id`)
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_spell` (
  `id` bigint(20) NOT NULL DEFAULT '0',
  `Category` bigint(20) NOT NULL COMMENT 'Category',
  `Dispel` bigint(20) NOT NULL COMMENT 'Dispel',
  `Mechanic` bigint(20) NOT NULL COMMENT 'Mechanic',
  `Attributes` bigint(20) NOT NULL COMMENT 'Attributes',
  `AttributesEx` bigint(20) NOT NULL COMMENT 'AttributesEx',
  `AttributesEx2` bigint(20) NOT NULL COMMENT 'AttributesEx2',
  `AttributesEx3` bigint(20) NOT NULL COMMENT 'AttributesEx3',
  `AttributesEx4` bigint(20) NOT NULL COMMENT 'AttributesEx4',
  `AttributesEx5` bigint(20) NOT NULL COMMENT 'AttributesEx5',
  `AttributesEx6` bigint(20) NOT NULL COMMENT 'AttributesEx6',
  `unk_320_1` bigint(20) NOT NULL COMMENT 'unk_320_1',
  `Stances` bigint(20) NOT NULL COMMENT 'Stances',
  `unk_320_2` bigint(20) NOT NULL COMMENT 'unk_320_2',
  `StancesNot` bigint(20) NOT NULL COMMENT 'StancesNot',
  `unk_320_3` bigint(20) NOT NULL COMMENT 'unk_320_3',
  `Targets` bigint(20) NOT NULL COMMENT 'Targets',
  `TargetCreatureType` bigint(20) NOT NULL COMMENT 'TargetCreatureType',
  `RequiresSpellFocus` bigint(20) NOT NULL COMMENT 'RequiresSpellFocus',
  `FacingCasterFlags` bigint(20) NOT NULL COMMENT 'FacingCasterFlags',
  `CasterAuraState` bigint(20) NOT NULL COMMENT 'CasterAuraState',
  `TargetAuraState` bigint(20) NOT NULL COMMENT 'TargetAuraState',
  `CasterAuraStateNot` bigint(20) NOT NULL COMMENT 'CasterAuraStateNot',
  `TargetAuraStateNot` bigint(20) NOT NULL COMMENT 'TargetAuraStateNot',
  `casterAuraSpell` bigint(20) NOT NULL COMMENT 'casterAuraSpell',
  `targetAuraSpell` bigint(20) NOT NULL COMMENT 'targetAuraSpell',
  `excludeCasterAuraSpell` bigint(20) NOT NULL COMMENT 'excludeCasterAuraSpell',
  `excludeTargetAuraSpell` bigint(20) NOT NULL COMMENT 'excludeTargetAuraSpell',
  `CastingTimeIndex` bigint(20) NOT NULL COMMENT 'CastingTimeIndex',
  `RecoveryTime` bigint(20) NOT NULL COMMENT 'RecoveryTime',
  `CategoryRecoveryTime` bigint(20) NOT NULL COMMENT 'CategoryRecoveryTime',
  `InterruptFlags` bigint(20) NOT NULL COMMENT 'InterruptFlags',
  `AuraInterruptFlags` bigint(20) NOT NULL COMMENT 'AuraInterruptFlags',
  `ChannelInterruptFlags` bigint(20) NOT NULL COMMENT 'ChannelInterruptFlags',
  `procFlags` bigint(20) NOT NULL COMMENT 'procFlags',
  `procChance` bigint(20) NOT NULL COMMENT 'procChance',
  `procCharges` bigint(20) NOT NULL COMMENT 'procCharges',
  `maxLevel` bigint(20) NOT NULL COMMENT 'maxLevel',
  `baseLevel` bigint(20) NOT NULL COMMENT 'baseLevel',
  `spellLevel` bigint(20) NOT NULL COMMENT 'spellLevel',
  `DurationIndex` bigint(20) NOT NULL COMMENT 'DurationIndex',
  `powerType` bigint(20) NOT NULL COMMENT 'powerType',
  `manaCost` bigint(20) NOT NULL COMMENT 'manaCost',
  `manaCostPerlevel` bigint(20) NOT NULL COMMENT 'manaCostPerlevel',
  `manaPerSecond` bigint(20) NOT NULL COMMENT 'manaPerSecond',
  `manaPerSecondPerLevel` bigint(20) NOT NULL COMMENT 'manaPerSecondPerLevel',
  `rangeIndex` bigint(20) NOT NULL COMMENT 'rangeIndex',
  `speed` bigint(20) NOT NULL COMMENT 'speed',
  `modalNextSpell` bigint(20) NOT NULL COMMENT 'modalNextSpell',
  `StackAmount` bigint(20) NOT NULL COMMENT 'StackAmount',
  `Totem_1` bigint(20) NOT NULL COMMENT 'Totem_1',
  `Totem_2` bigint(20) NOT NULL COMMENT 'Totem_2',
  `Reagent_1` bigint(20) NOT NULL COMMENT 'Reagent_1',
  `Reagent_2` bigint(20) NOT NULL COMMENT 'Reagent_2',
  `Reagent_3` bigint(20) NOT NULL COMMENT 'Reagent_3',
  `Reagent_4` bigint(20) NOT NULL COMMENT 'Reagent_4',
  `Reagent_5` bigint(20) NOT NULL COMMENT 'Reagent_5',
  `Reagent_6` bigint(20) NOT NULL COMMENT 'Reagent_6',
  `Reagent_7` bigint(20) NOT NULL COMMENT 'Reagent_7',
  `Reagent_8` bigint(20) NOT NULL COMMENT 'Reagent_8',
  `ReagentCount_1` bigint(20) NOT NULL COMMENT 'ReagentCount_1',
  `ReagentCount_2` bigint(20) NOT NULL COMMENT 'ReagentCount_2',
  `ReagentCount_3` bigint(20) NOT NULL COMMENT 'ReagentCount_3',
  `ReagentCount_4` bigint(20) NOT NULL COMMENT 'ReagentCount_4',
  `ReagentCount_5` bigint(20) NOT NULL COMMENT 'ReagentCount_5',
  `ReagentCount_6` bigint(20) NOT NULL COMMENT 'ReagentCount_6',
  `ReagentCount_7` bigint(20) NOT NULL COMMENT 'ReagentCount_7',
  `ReagentCount_8` bigint(20) NOT NULL COMMENT 'ReagentCount_8',
  `EquippedItemClass` bigint(20) NOT NULL COMMENT 'EquippedItemClass',
  `EquippedItemSubClassMask` bigint(20) NOT NULL COMMENT 'EquippedItemSubClassMask',
  `EquippedItemInventoryTypeMask` bigint(20) NOT NULL COMMENT 'EquippedItemInventoryTypeMask',
  `Effect_1` bigint(20) NOT NULL COMMENT 'Effect_1',
  `Effect_2` bigint(20) NOT NULL COMMENT 'Effect_2',
  `Effect_3` bigint(20) NOT NULL COMMENT 'Effect_3',
  `EffectDieSides_1` bigint(20) NOT NULL COMMENT 'EffectDieSides_1',
  `EffectDieSides_2` bigint(20) NOT NULL COMMENT 'EffectDieSides_2',
  `EffectDieSides_3` bigint(20) NOT NULL COMMENT 'EffectDieSides_3',
  `EffectBaseDice_1` bigint(20) NOT NULL,
  `EffectBaseDice_2` bigint(20) NOT NULL,
  `EffectBaseDice_3` bigint(20) NOT NULL,
  `EffectRealPointsPerLevel_1` bigint(20) NOT NULL COMMENT 'EffectRealPointsPerLevel_1',
  `EffectRealPointsPerLevel_2` bigint(20) NOT NULL COMMENT 'EffectRealPointsPerLevel_2',
  `EffectRealPointsPerLevel_3` bigint(20) NOT NULL COMMENT 'EffectRealPointsPerLevel_3',
  `EffectBasePoints_1` bigint(20) NOT NULL COMMENT 'EffectBasePoints_1',
  `EffectBasePoints_2` bigint(20) NOT NULL COMMENT 'EffectBasePoints_2',
  `EffectBasePoints_3` bigint(20) NOT NULL COMMENT 'EffectBasePoints_3',
  `EffectMechanic_1` bigint(20) NOT NULL COMMENT 'EffectMechanic_1',
  `EffectMechanic_2` bigint(20) NOT NULL COMMENT 'EffectMechanic_2',
  `EffectMechanic_3` bigint(20) NOT NULL COMMENT 'EffectMechanic_3',
  `EffectImplicitTargetA_1` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetA_1',
  `EffectImplicitTargetA_2` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetA_2',
  `EffectImplicitTargetA_3` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetA_3',
  `EffectImplicitTargetB_1` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetB_1',
  `EffectImplicitTargetB_2` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetB_2',
  `EffectImplicitTargetB_3` bigint(20) NOT NULL COMMENT 'EffectImplicitTargetB_3',
  `EffectRadiusIndex_1` bigint(20) NOT NULL COMMENT 'EffectRadiusIndex_1',
  `EffectRadiusIndex_2` bigint(20) NOT NULL COMMENT 'EffectRadiusIndex_2',
  `EffectRadiusIndex_3` bigint(20) NOT NULL COMMENT 'EffectRadiusIndex_3',
  `EffectApplyAuraName_1` bigint(20) NOT NULL COMMENT 'EffectApplyAuraName_1',
  `EffectApplyAuraName_2` bigint(20) NOT NULL COMMENT 'EffectApplyAuraName_2',
  `EffectApplyAuraName_3` bigint(20) NOT NULL COMMENT 'EffectApplyAuraName_3',
  `EffectAmplitude_1` bigint(20) NOT NULL COMMENT 'EffectAmplitude_1',
  `EffectAmplitude_2` bigint(20) NOT NULL COMMENT 'EffectAmplitude_2',
  `EffectAmplitude_3` bigint(20) NOT NULL COMMENT 'EffectAmplitude_3',
  `EffectMultipleValue_1` bigint(20) NOT NULL COMMENT 'EffectMultipleValue_1',
  `EffectMultipleValue_2` bigint(20) NOT NULL COMMENT 'EffectMultipleValue_2',
  `EffectMultipleValue_3` bigint(20) NOT NULL COMMENT 'EffectMultipleValue_3',
  `EffectChainTarget_1` bigint(20) NOT NULL COMMENT 'EffectChainTarget_1',
  `EffectChainTarget_2` bigint(20) NOT NULL COMMENT 'EffectChainTarget_2',
  `EffectChainTarget_3` bigint(20) NOT NULL COMMENT 'EffectChainTarget_3',
  `EffectItemType_1` bigint(20) NOT NULL COMMENT 'EffectItemType_1',
  `EffectItemType_2` bigint(20) NOT NULL COMMENT 'EffectItemType_2',
  `EffectItemType_3` bigint(20) NOT NULL COMMENT 'EffectItemType_3',
  `EffectMiscValue_1` bigint(20) NOT NULL COMMENT 'EffectMiscValue_1',
  `EffectMiscValue_2` bigint(20) NOT NULL COMMENT 'EffectMiscValue_2',
  `EffectMiscValue_3` bigint(20) NOT NULL COMMENT 'EffectMiscValue_3',
  `EffectMiscValueB_1` bigint(20) NOT NULL COMMENT 'EffectMiscValueB_1',
  `EffectMiscValueB_2` bigint(20) NOT NULL COMMENT 'EffectMiscValueB_2',
  `EffectMiscValueB_3` bigint(20) NOT NULL COMMENT 'EffectMiscValueB_3',
  `EffectTriggerSpell_1` bigint(20) NOT NULL COMMENT 'EffectTriggerSpell_1',
  `EffectTriggerSpell_2` bigint(20) NOT NULL COMMENT 'EffectTriggerSpell_2',
  `EffectTriggerSpell_3` bigint(20) NOT NULL COMMENT 'EffectTriggerSpell_3',
  `EffectPointsPerComboPoint_1` bigint(20) NOT NULL COMMENT 'EffectPointsPerComboPoint_1',
  `EffectPointsPerComboPoint_2` bigint(20) NOT NULL COMMENT 'EffectPointsPerComboPoint_2',
  `EffectPointsPerComboPoint_3` bigint(20) NOT NULL COMMENT 'EffectPointsPerComboPoint_3',
  `EffectSpellClassMaskA_1` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskA_1',
  `EffectSpellClassMaskA_2` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskA_2',
  `EffectSpellClassMaskA_3` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskA_3',
  `EffectSpellClassMaskB_1` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskB_1',
  `EffectSpellClassMaskB_2` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskB_2',
  `EffectSpellClassMaskB_3` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskB_3',
  `EffectSpellClassMaskC_1` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskC_1',
  `EffectSpellClassMaskC_2` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskC_2',
  `EffectSpellClassMaskC_3` bigint(20) NOT NULL COMMENT 'EffectSpellClassMaskC_3',
  `SpellVisual_1` bigint(20) NOT NULL COMMENT 'SpellVisual_1',
  `SpellVisual_2` bigint(20) NOT NULL COMMENT 'SpellVisual_2',
  `SpellIconID` bigint(20) NOT NULL COMMENT 'SpellIconID',
  `activeIconID` bigint(20) NOT NULL COMMENT 'activeIconID',
  `spellPriority` bigint(20) NOT NULL COMMENT 'spellPriority',
  `SpellName_en_gb` text,
  `SpellName_2` text NOT NULL COMMENT 'SpellName_2',
  `SpellName_fr_fr` text,
  `SpellName_de_de` text,
  `SpellName_5` text NOT NULL COMMENT 'SpellName_5',
  `SpellName_6` text NOT NULL COMMENT 'SpellName_6',
  `SpellName_es_es` text,
  `SpellName_8` text NOT NULL COMMENT 'SpellName_8',
  `SpellName_ru_ru` text,
  `SpellName_10` text NOT NULL COMMENT 'SpellName_10',
  `SpellName_11` text NOT NULL COMMENT 'SpellName_11',
  `SpellName_12` text NOT NULL COMMENT 'SpellName_12',
  `SpellName_13` text NOT NULL COMMENT 'SpellName_13',
  `SpellName_14` text NOT NULL COMMENT 'SpellName_14',
  `SpellName_15` text NOT NULL COMMENT 'SpellName_15',
  `SpellName_16` text NOT NULL COMMENT 'SpellName_16',
  `SpellNameFlag` bigint(20) NOT NULL COMMENT 'SpellNameFlag',
  `Rank_1` text NOT NULL COMMENT 'Rank_1',
  `Rank_2` text NOT NULL COMMENT 'Rank_2',
  `Rank_fr_fr` text,
  `Rank_de_de` text,
  `Rank_5` text NOT NULL COMMENT 'Rank_5',
  `Rank_6` text NOT NULL COMMENT 'Rank_6',
  `Rank_es_es` text,
  `Rank_8` text NOT NULL COMMENT 'Rank_8',
  `Rank_ru_ru` text,
  `Rank_10` text NOT NULL COMMENT 'Rank_10',
  `Rank_11` text NOT NULL COMMENT 'Rank_11',
  `Rank_12` text NOT NULL COMMENT 'Rank_12',
  `Rank_13` text NOT NULL COMMENT 'Rank_13',
  `Rank_14` text NOT NULL COMMENT 'Rank_14',
  `Rank_15` text NOT NULL COMMENT 'Rank_15',
  `Rank_16` text NOT NULL COMMENT 'Rank_16',
  `RankFlags` bigint(20) NOT NULL COMMENT 'RankFlags',
  `Description_en_gb` text,
  `Description_2` text NOT NULL COMMENT 'Description_2',
  `Description_fr_fr` text,
  `Description_de_de` text,
  `Description_5` text NOT NULL COMMENT 'Description_5',
  `Description_6` text NOT NULL COMMENT 'Description_6',
  `Description_es_es` text,
  `Description_8` text NOT NULL COMMENT 'Description_8',
  `Description_ru_ru` text,
  `Description_10` text NOT NULL COMMENT 'Description_10',
  `Description_11` text NOT NULL COMMENT 'Description_11',
  `Description_12` text NOT NULL COMMENT 'Description_12',
  `Description_13` text NOT NULL COMMENT 'Description_13',
  `Description_14` text NOT NULL COMMENT 'Description_14',
  `Description_15` text NOT NULL COMMENT 'Description_15',
  `Description_16` text NOT NULL COMMENT 'Description_16',
  `DescriptionFlags` bigint(20) NOT NULL COMMENT 'DescriptionFlags',
  `ToolTip_1` text NOT NULL COMMENT 'ToolTip_1',
  `ToolTip_2` text NOT NULL COMMENT 'ToolTip_2',
  `Tooltip_fr_fr` text,
  `Tooltip_de_de` text,
  `ToolTip_5` text NOT NULL COMMENT 'ToolTip_5',
  `ToolTip_6` text NOT NULL COMMENT 'ToolTip_6',
  `Tooltip_es_es` text,
  `ToolTip_8` text NOT NULL COMMENT 'ToolTip_8',
  `Tooltip_ru_ru` text,
  `ToolTip_10` text NOT NULL COMMENT 'ToolTip_10',
  `ToolTip_11` text NOT NULL COMMENT 'ToolTip_11',
  `ToolTip_12` text NOT NULL COMMENT 'ToolTip_12',
  `ToolTip_13` text NOT NULL COMMENT 'ToolTip_13',
  `ToolTip_14` text NOT NULL COMMENT 'ToolTip_14',
  `ToolTip_15` text NOT NULL COMMENT 'ToolTip_15',
  `ToolTip_16` text NOT NULL COMMENT 'ToolTip_16',
  `ToolTipFlags` bigint(20) NOT NULL COMMENT 'ToolTipFlags',
  `ManaCostPercentage` bigint(20) NOT NULL COMMENT 'ManaCostPercentage',
  `StartRecoveryCategory` bigint(20) NOT NULL COMMENT 'StartRecoveryCategory',
  `StartRecoveryTime` bigint(20) NOT NULL COMMENT 'StartRecoveryTime',
  `MaxTargetLevel` bigint(20) NOT NULL COMMENT 'MaxTargetLevel',
  `SpellFamilyName` bigint(20) NOT NULL COMMENT 'SpellFamilyName',
  `SpellFamilyFlags` bigint(20) NOT NULL COMMENT 'SpellFamilyFlags',
  `SpellFamilyFlags2` bigint(20) NOT NULL COMMENT 'SpellFamilyFlags2',
  `MaxAffectedTargets` bigint(20) NOT NULL COMMENT 'MaxAffectedTargets',
  `DmgClass` bigint(20) NOT NULL COMMENT 'DmgClass',
  `PreventionType` bigint(20) NOT NULL COMMENT 'PreventionType',
  `StanceBarOrder` bigint(20) NOT NULL COMMENT 'StanceBarOrder',
  `DmgMultiplier_1` bigint(20) NOT NULL COMMENT 'DmgMultiplier_1',
  `DmgMultiplier_2` bigint(20) NOT NULL COMMENT 'DmgMultiplier_2',
  `DmgMultiplier_3` bigint(20) NOT NULL COMMENT 'DmgMultiplier_3',
  `MinFactionId` bigint(20) NOT NULL COMMENT 'MinFactionId',
  `MinReputation` bigint(20) NOT NULL COMMENT 'MinReputation',
  `RequiredAuraVision` bigint(20) NOT NULL COMMENT 'RequiredAuraVision',
  `TotemCategory_1` bigint(20) NOT NULL COMMENT 'TotemCategory_1',
  `TotemCategory_2` bigint(20) NOT NULL COMMENT 'TotemCategory_2',
  `AreaGroupId` bigint(20) NOT NULL COMMENT 'AreaGroupId',
  `SchoolMask` bigint(20) NOT NULL COMMENT 'SchoolMask',
  `runeCostID` bigint(20) NOT NULL COMMENT 'runeCostID',
  `spellMissileID` bigint(20) NOT NULL COMMENT 'spellMissileID',
  `PowerDisplayId` bigint(20) NOT NULL COMMENT 'PowerDisplayId',
  `unk_320_4_1` bigint(20) NOT NULL COMMENT 'unk_320_4_1',
  `unk_320_4_2` bigint(20) NOT NULL COMMENT 'unk_320_4_2',
  `unk_320_4_3` bigint(20) NOT NULL COMMENT 'unk_320_4_3',
  `spellDescriptionVariableID` bigint(20) NOT NULL COMMENT 'spellDescriptionVariableID',
  `SpellDifficultyId` bigint(20) NOT NULL COMMENT 'SpellDifficultyId',
  `f_234` bigint(20) NOT NULL COMMENT 'f_234',
  PRIMARY KEY (`id`)
) ENGINE=MyISAM DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_spell_duration` (
  `id` int(11) NOT NULL,
  `duration_1` int(11) DEFAULT NULL,
  `duration_2` int(11) DEFAULT NULL,
  `duration_3` int(11) DEFAULT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
","
CREATE TABLE IF NOT EXISTS `^12340_spell_radius` (
  `id` int(11) NOT NULL,
  `radius_1` int(11) NOT NULL,
  `radius_2` int(11) NOT NULL,
  `radius_3` int(11) NOT NULL
) ENGINE=InnoDB DEFAULT CHARSET=utf8;
");